### ISSUE TITLE
Component manager blocked

### ISSUE THREAD

**Issue by Drifti** [Magento2Translations/language_nl_nl#3]
Installing in Magento 2.1.2 by 

cd <your magento path>
composer require magento2translations/language_nl_nl:dev-master
php bin/magento cache:clean

leads in hang up of the component manager in System, Web Setup Wizard.

The same with es_es Version.

**Comment by MrGekko** [comment]
I am sorry for the late reply... But If i understand the Web Setup Wizard correctly it is a composer replacement. So it doesn't do anything that composer cant. Could you tell me why you need Web Setup Wizard? And could you send me a screenshot of what happens, and maybe a error log of what went wrong. I suspect it has something to do with the fact that this repo doesn't have any tags..

**Comment by Drifti** [comment]
I did not use the component manager for installing "Magento2Translations/language_es_es".
I installed "Magento2Translations/language_es_es" with composer as descibed obove and as descibed in your installation advice.

But I need the component manager for other reasons. It is a important part of the Magento 2 Backend.
For example to install free and payed extension from marketplace.magento.com
http://devdocs.magento.com/guides/v2.1/comp-mgr/module-man/compman-start.html

After installation of "Magento2Translations/language_es_es", the component Manager hang up, please try yourself.
When "Magento2Translations/language_es_es" is deleted again, the funktion of component Manager is normal again.
You find it in in Backend > Web Setup Wizard > component Manager
Please try yourself before and after installation

**Comment by MrGekko** [comment]
There are allot of issues with the component manager. https://github.com/magento/magento2/issues/6621 https://github.com/magento/magento2/issues/6737 https://github.com/magento/magento2/issues/6078 
I don't think that this is in any way related to this package. And I cannot test this myself due to my nginx setup. If you have figured out what the real problem is (check the logs do a compile on magento) I can try and fix this for you.
